# Generated by Django 6.0.3 on 2026-04-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
