# Generated by Django 6.0.3 on 2026-04-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_car_image_alter_car_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
