# Generated by Django 6.0.3 on 2026-04-26 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov'])], verbose_name='videos/'),
        ),
    ]
